# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# Using and caching packrat package dir: https://discuss.ropensci.org/t/reproducibility-in-r-package-building-with-travis-and-packrat/445/5
#directories: $TRAVIS_BUILD_DIR/packrat/
#install:
#  - R -e "0" --args --bootstrap-packrat
language: R
sudo: false
cache:
  packages: true
warnings_are_errors: false
r_check_args: "--no-vignettes"1
cache:
  directories:
    - ~/Rlib
install:
  - wget https://pluto.coe.fsu.edu/svn/common/RNetica/releases/RNetica_0.4-6.tgz -O '/tmp/RNetica_0.4-6.tgz'
  - tar -xvf '/tmp/RNetica_0.4-6.tgz'
  - cd '/tmp/RNetica/'
  - R CMD install RNetica --configure-args='--with-netica=/home/travis/build/egouldo/GrasslandAllocatr/src/Netica_API_504'
  - cd ../
  - Rscript -e 'install.packages(c("devtools", "knitr", "dplyr", "purrr", "readr", "rprojroot", "tidyr", "rmarkdown"))'

