# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# Using and caching packrat package dir: https://discuss.ropensci.org/t/reproducibility-in-r-package-building-with-travis-and-packrat/445/5
#directories: $TRAVIS_BUILD_DIR/packrat/
#install:
#  - R -e "0" --args --bootstrap-packrat
language: R
sudo: false
dist: trusty
cache:
  packages: false
warnings_are_errors: false
