#' Loads Netica network into R and NeticaAPI memory and compiles network
#'
#' @param path a character string containing the path to the Netica file, in either \code{.dne} or \code{.neta} format.
#'
#' @return grassland_bbn the R object of network in NeticaAPI memory.
#' @export
#' @import RNetica
#'
load_compile_grassland_bbn <- function(path = character) {
        grassland_bbn <- RNetica::ReadNetworks(path)
        RNetica::CompileNetwork(grassland_bbn)
        RNetica::ClearAllErrors() # clear errors generated by missing MPT's for parent nodes
        return(grassland_bbn)
}