# Define Functions
load_Netica_LicenseKey <- function(path = "./data/LicenseKey"){
        load(GrasslandAllocatr::f_path(path))
        RNetica::StartNetica(license = LicenseKey)
}

load_compile_grassland_bbn <- function(path = character) {
        grassland_bbn <- RNetica::ReadNetworks(path)
        CompileNetwork(grassland_bbn)
        ClearAllErrors() # clear errors generated by missing MPT's for parent nodes
        return(grassland_bbn)
}
# Stop and Restart Netica with License Key
StopNetica()
load_Netica_LicenseKey()